version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: 'always'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=barber-shop
    volumes:
      - barber_pg_data:/bitnami/postgresql
    ports:
      - "5432:5432"
  
  api:
    container_name: api-container
    build: .
    restart: always
    image: barber-shop-api
    command: npm start
    volumes: 
       - ./dist:/usr/src/barber-shop-api/dist
       - ./prisma:/usr/src/barber-shop-api/prisma
    ports: 
      - '3333:3333'
    links:
        - postgres
    depends_on:
      - postgres   

volumes:
  barber_pg_data: