version: '3.7'

services:
  postgres:
    image: postgres:16.3-alpine3.19
    restart: 'always'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=barber-shop
    volumes:
      - barber_pg_data:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - barber_shop
  
  api:
    container_name: api-container
    build: .
    restart: always
    image: barber-shop-api
    command: npm start
    ports: 
      - '3333:3333'
    depends_on:
      - postgres
    networks:
      - barber_shop

networks:
  barber_shop:
    driver: bridge

volumes:
  barber_pg_data: