
POST http://localhost:5555/api/signup
content-type: application/json

{
    "name": "any_name",
    "email": "wesleyemail@mail.com",
    "password": "Pass123#",
    "phone": "any_phone"
}

###

POST http://localhost:5555/api/login
content-type: application/json

{
    "email": "wesleyemail@mail.com",
    "password": "Pass123#"
}