
POST https://barber-shop-api.onrender.com/api/signup
content-type: application/json

{
    "name": "any_name",
    "email": "wesleyemail@mail.com",
    "password": "Pass123#",
    "phone": "any_phone"
}